### PR TITLE
[WIP] Filter creation

### PR DESCRIPTION
**Pull request by lontivero**
This PR contains the code for creating filter for blocks when Bitcoin Core node notifies us about the acceptance of a new incomming block. Basically, every time our Bitcoin Core node receives a new valid incomming block, it executes a `curl` command as follow: `curl http://localhost:32127/api/v1/btc/Blockchain/block/{acceptedBlockHash}`

In order to achieve that, the `bitcoin.conf` config file needs to hace the following entry: `blocknotify=curl http://localhost:32127/api/v1/btc/Blockchain/block/%s`

Most of the code in this PR is about testing the all the involved components together, this is the Bitcoin Core node (in regtest) receiving blocks with p2wpkh and notifying to our backend API which  
creates an persists the filters. Last, it validates that the created filters can match the addresses in the wallet.

NOTE: while testing all this integrated i found concurrency problems when more than one thread tries to write the filters at the same time. I will work on improving that.

### CODE REVIEW

**Comment by nopara73** [comment]
> NOTE: while testing all this integrated i found concurrency problems when more than one thread tries to write the filters at the same time. I will work on improving that.

Alright, I added a Work In Progress tag to the PR.

After concurrency is resolved, is it ok if I make a PR against this branch of yours? So to keep code coherence and then you can review it?

**Comment by lontivero** [comment]
Yes, sure.

**Comment by nopara73** [comment]
The CI is still not fixed.  
Also note, even if you fix the CI, travis'll probably be still not fixed, for that merge the master. The problem was tests were taking 10+ minutes without producing output and there was a clean fix travis recommended, so I fixed it.  

About concurrency: yes, lock is a good, because it's simple.  
Here's my policy on concurrency stuff:
1. If accurate data is not that important and you can get away with a concurrent collection then use it.
2. Use locks, usually use the locks, if you are in async context then use the lock of Stephen Cleary's AsyncEx library, because its sync lock has an async lock pair, very handy. `AsyncLock MyDicLock` `using(MyDicLock.Lock()){locked code}`, and `using(await MyDicLock.LockAsync()`.
3. If lock is not performant enough, then Interlocked is preferable and the most performant of all, failing that readerwriterlock can be applied to some situation, it's also in Cleary's library, and never use the dotnet readerwriterlocks.

**Comment by nopara73** [comment]
That being said, I'm ok with anything that works well.

**Comment by nopara73** [comment]
This PR can be closed after issue is resolved: https://github.com/nopara73/MagicalCryptoWallet/issues/43

**Comment by lontivero** [comment]
There is a new PR for this topic https://github.com/nopara73/MagicalCryptoWallet/pull/84.

**Pull request closed without merging**
